sudo: required
os:
- linux
- osx
dist: trusty
osx_image: xcode8
language: node_js
node_js: '7'
before_install:
 - chmod +x ./Build-All.sh
 - "npm install electron-packager -g" 
script: ./Build-All.sh
