notifications:
  email: true
  
language: node_js

node_js:
  - '7'

cache: 
  directories:
    - node_modules

os:
  - linux

dist: trusty

before_install:
  - node --version
  - brew update
  - brew install wine
  - wine --version
  - chmod +x ./Build-All.sh
  - "npm install electron-packager -g" 

deploy:
  provider: releases
  
script: './Build-All.sh'

branches:
  only:
    - master  