notifications:
  email: true
  
language: node_js
cache: 
  directories:
    - node_modules
    
env:
  - NODE_VERSION="7.5"
  
before_install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use --delete-prefix $NODE_VERSION
  - node --version
 
os:
  - osx
  
osx_image: xcode7.3

dist: trusty

before_install:
  - brew update
  - brew install wine
  - wine --version
  - chmod +x ./Build-All.sh
  - "npm install electron-packager -g" 

deploy:
  provider: releases
  
script: './Build-All.sh'

branches:
  only:
    - master  