version: 1.0.0-{build}

# Branches
branches:
  only:
  - master

# Set the Node Version
environment:
  matrix:
    - nodejs_version: "7"
    
# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version 
  - npm -g install node-gyp@3.6.2
  - npm -g install electron-packager
  - npm -g install archiver
  - .\Build.bat
      
# Deployment Options
before_deploy:
  - node .\Tools\PackageBuild.js
  - ps: Get-ChildItem .\Build\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

deploy:
  tag: 1.0.0
  release: 'DSTEd v1.0.0 (Build: ${APPVEYOR_BUILD_NUMBER}) - Pre-Release (Preview)'
  description: ' ![Preview](https://github.com/DST-Tools/DSTEd/raw/master/Screenshots/preview.png)  ## Pre-Release v1.0.0 (Preview) Builded binarys for `Windows` (`32bit` & `64bit`), `Linux` (`32bit`, `64bit` & `armv7`) and `Mac OS X` (`darwin` & `mas`, only `64bit`).'
  provider: GitHub
  auth_token:
    secure: V9hufIe4lJghIoqzu0XMfsay/OP+rXjO6CgNoQ1m9mc2oinsCgz+Y5UK0/6y0GLa
  artifact: 
  draft: false
  prerelease: true
  force_update: true
    
matrix:
  fast_finish: true

clone_depth: 1
max_jobs: 10
  
# Disable other
build: OFF
test: OFF