version: 1.0.0-{build}

# Debugging
#init:
#    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# Fuck'd up the shit variables; Can't set on the Backend, must be set here oÔ
environment:
  GITHUB_LANG_TOKEN:
    secure: 8hrb5tdiQ8e08hGu/8KhcwhuHUcakMkWR7HgRH+HgRWfinwNM5vzjNk2sdnDpdEO
  LANG_DIR: C:\Lang-Temp
  
# Branches
branches:
  only:
  - master

# Installation
install:
  - ps: Install-Product node $env:nodejs_version
  - .\I18N.bat
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GITHUB_LANG_TOKEN)@github.com`n"
  - git config --global user.email "build@DSTEd.net"
  - git config --global user.name "[DSTEd] Build Server"
  #- mkdir %LANG_DIR%
  - git clone https://%GITHUB_LANG_TOKEN%:x-oauth-basic@github.com/DST-Tools/DSTEd-Languages.git %LANG_DIR%
  - git --work-tree=%LANG_DIR% remote set-url origin https://%GITHUB_LANG_TOKEN%:x-oauth-basic@github.com/DST-Tools/DSTEd-Languages.
  - git --work-tree=%LANG_DIR% checkout origin master
  - cp .\en_US.json %LANG_DIR%\xx_XX.json
  - git --work-tree=%LANG_DIR% add xx_XX.json
  - git --work-tree=%LANG_DIR% commit -m "[AutoUpdate] Default Language (xx_XX.json)"
  - git --work-tree=%LANG_DIR% push origin HEAD:master
  - npm -g install node-gyp@3.6.2
  - npm -g install electron-packager
  - npm -g install archiver
  - .\Build-All.bat

# Deployment Options
before_deploy:
  - node .\Tools\PackageBuild.js
  - ps: Get-ChildItem .\Build\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
    
matrix:
  fast_finish: true

clone_depth: 1
max_jobs: 10

# Disable other
build: OFF
test: OFF