version: 1.0.0-{build}

# Set the Node Version
environment:
  matrix:
    - nodejs_version: "7"
    - appveyor_repo_tag: true
    
# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version 
  - npm -g install node-gyp@3.6.2
  - npm -g install electron-packager
  - npm -g install archiver
  - .\Build.bat
  
# Deployment Options
before_deploy:
  - node .\Tools\PackageBuild.js

deploy:
  tag: $(appveyor_build_version)
  release: 'DSTEd v${appveyor_build_version} - Pre-Release (Preview)'
  description: ' ![Preview](https://github.com/DST-Tools/DSTEd/raw/master/Screenshots/preview.png)  ## Pre-Release v1.0.0 (Preview) Builded binarys for `Windows` (`32bit` & `64bit`), `Linux` (`32bit`, `64bit` & `armv7`) and `Mac OS X` (`darwin` & `mas`, only `64bit`).'
  provider: GitHub
  auth_token:
    secure: b202f536350628ff69af69d08daee9f76a9cff20
  artifact: '*.zip'
  draft: false
  prerelease: true
  on:
    appveyor_repo_tag: true

# Branches
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/
    
matrix:
  fast_finish: true

# Disable other
build: OFF
test: OFF