version: 1.0.0-{build}

# Set the Node Version
environment:
  matrix:
    - nodejs_version: "7"
    
# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version 
  - npm -g install electron-packager
  - .\Build-All.bat
  
matrix:
  fast_finish: true
  
build: OFF
test: OFF
deploy: OFF