version: 1.0.0-{build}

# Init
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
# Set the Node Version
environment:
  matrix:
    - nodejs_version: "7"
    
# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version 
  - npm -g install electron-packager
  - npm -g install archiver
  - ps: .\Build.bat
  
# Deployment Options
deploy:
  tag: $(appveyor_build_version)
  release: 'DSTEd v${appveyor_build_version} - Pre-Release (Preview)'
  description: ' ![Preview](https://github.com/DST-Tools/DSTEd/raw/master/Screenshots/preview.png)  ## Pre-Release v1.0.0 (Preview) Builded binarys for `Windows` (`32bit` & `64bit`), `Linux` (`32bit`, `64bit` & `armv7`) and `Mac OS X` (`darwin` & `mas`, only `64bit`).'
  provider: GitHub
  auth_token:
    secure: b202f536350628ff69af69d08daee9f76a9cff20
  artifact: '*.zip'
  draft: false
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
    
matrix:
  fast_finish: true

build: OFF
test: OFF