version: 1.0.0-{build}

init:
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# Branches
branches:
  only:
  - master

# Set the Node Version
environment:
  matrix:
    - nodejs_version: "7"
    
# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version 
  - npm -g install node-gyp@3.6.2
  - npm -g install electron-packager
  - npm -g install archiver
  - .\Build-All.bat
  - .\I18N.bat

# Push default language file
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$env:GITHUB_AUTH_TOKEN:x-oauth-basic@github.com`n"
  - git config --global user.email "build@DSTEd.net"
  - git config --global user.name "[DSTEd] Build Server"
  - mkdir Temp-Language
  - git clone https://github.com/DST-Tools/DSTEd-Languages.git .\Temp-Language
  - cp .\en_US.json .\Temp-Language\xx_XX.json
  - cd .\Temp-Language; git add xx_XX.json; git commit -m "[AutoUpdate] Default language (xx_XX.json)"; git push
    
# Deployment Options
before_deploy:
  - node .\Tools\PackageBuild.js
  - ps: Get-ChildItem .\Build\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
    
matrix:
  fast_finish: true

clone_depth: 1
max_jobs: 10

# Disable other
build: OFF
test: OFF